{% set python_min = "3.10" %}
{% set name = "strands-agents-tools" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/strands_agents_tools-{{ version }}.tar.gz
  sha256: 4b7d8141253be04674a0fb7592c531257cc7e5a84590f3ddb2117ec1ac67c6de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - strands-agents >=0.1.0,<1.0.0
    - rich >=14.0.0,<15.0.0
    - sympy >=1.12.0,<2.0.0
    - prompt-toolkit <4.0.0,>=3.0.51
    - colorama >=0.4.6,<0.5.0
    - aws-requests-auth >=0.4.3,<0.5.0
    - pyjwt >=2.10.1,<3.0.0
    - dill >=0.4.0,<0.5.0
    - pillow >=11.2.1,<12.0.0
    - tenacity >=9.1.2,<10.0.0
    - watchdog >=6.0.0,<7.0.0
    - slack-bolt >=1.23.0,<2.0.0
    - python-tzdata

test:
  imports:
    - strands_tools
    - strands_tools.calculator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://strandsagents.com/latest/
  summary: A collection of specialized tools for Strands Agents
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://strandsagents.com/latest/user-guide/concepts/tools/tools_overview/
  dev_url: https://github.com/strands-agents

extra:
  recipe-maintainers:
    - Unshure
    - athkulk
